### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by matthewgilbert** [tbrown122387/tbrown122387.github.io#1]
Firstly thanks for providing a great resource. It looks like you links are broken, possibly because of the templating engine. When I look at the links on the landing page I see the duplication such as the following

https://tbrown122387.github.io/tbrown122387.github.io/tbrown122387.github.io/courses/5170/

**Comment by tbrown122387** [comment]
More likely because of my school’s changing of how hosting is handled. We set up a redirect, and I probably forgot to change a url in a config file somewhere. I’ll take a look at it shortly

**Comment by tbrown122387** [comment]
@matthewgilbert works now :) thanks for the heads up

**Comment by tbrown122387** [comment]
@matthewgilbert thanks for spotting this I would've never noticed. Took some fiddling but it's fixed now.
